### ISSUE TITLE
Run on www/apache24 with www/mod_php8*

### ISSUE THREAD

**Issue by VVD** [clonos/clonos-ports-wip#9]
I see in documentation nginx + php_fpm only.
Can you add instruction how to run on www/apache24 + www/mod_php8*?

**Comment by olevole** [comment]
Currently it is not possible to use apache as some functionality ( VNC and upcoming Kubernetes clusters) uses specific NGINX settings and modules. 

It will be possible when we stabilize the API, but at the moment due to lack of resources we are forced to bind to nginx

**Comment by VVD** [comment]
Web server for VNC?… Just use VNC client to connect.
Kubernetes?… It's bhyve, isn't it? Why we need it here?
Maybe I misunderstood you, but your answer look very weird for me…

**Comment by olevole** [comment]
Mainly for STREAMS:
```
stream {

        include maps;
        include upstreams/*.conf;

        server {
                listen *:443;
                proxy_pass $name;
                ssl_preread on;
        }
}

```

ClonOS can generate chunks of nginx configuration. Also 'ssl_preread' allow you to choose upstream by SSL certs (used in K8S clusters)

**Comment by VVD** [comment]
I got server for virtualization (+1 or 2 more in several months)  and want to use bhyve on it. I don't need VNC web client, K8S clusters and etc. Just web management interface for bhyve on several servers. UI for hypervisor's API - something like phpvirtualbox. Proxmox, RHEV, VMware have some sort of web UI.
Maybe CloneOS is something else? I'm very new for CloneOS.

Thanks for your answers!
